name: test
on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
jobs:
  pint:
    name: Pint
    runs-on: ubuntu-latest
    steps:
      - name: Prepare PHP
        id: setup-php
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.4
          tools: composer:v2
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Composer dependencies
        run: composer install --no-interaction --no-ansi --no-progress
      - name: Run Pint
        run: ./vendor/bin/pint --test
  pest:
    name: Pest
    needs: pint
    runs-on: ubuntu-latest
    steps:
      - name: Prepare PHP
        id: setup-php
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.4
          tools: composer:v2
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Composer dependencies
        run: composer install --no-interaction --no-ansi --no-progress
      - name: Run tests
        run: ./vendor/bin/pest
