name: test
on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  pint:
    name: Pint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Prepare PHP
        id: setup-php
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.4
          tools: composer:v2
          cache: composer
      - name: Install Composer dependencies
        run: composer install --no-interaction --no-ansi --no-progress --prefer-dist
      - name: Run Pint
        run: ./vendor/bin/pint --test
  phpstan:
    name: PHPStan
    needs: pint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Prepare PHP
        id: setup-php
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.4
          tools: composer:v2
          cache: composer
      - name: Install Composer dependencies
        run: composer install --no-interaction --no-ansi --no-progress --prefer-dist
      - name: Run PHPStan
        run: ./vendor/bin/phpstan analyse --no-progress
  pest:
    name: Pest
    needs: pint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Prepare PHP
        id: setup-php
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.4
          tools: composer:v2
          cache: composer
      - name: Install Composer dependencies
        run: composer install --no-interaction --no-ansi --no-progress --prefer-dist
      - name: Run tests
        run: ./vendor/bin/pest
